# -*- coding: utf-8 -*-
"""signal_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L2tSd-VoA8x6XGlLpfs300XqG28Q0Nt-
"""

import numpy as np
import h5py
from scipy.signal import butter, filtfilt

# Load strain data from HDF5
def load_strain_data(file_path):
    with h5py.File(file_path, 'r') as f:
        strain = f['strain']['Strain'][:]
        time = f['strain']['Strain'].attrs['X']  # if time stored differently, adjust
    return strain, time


# Bandpass filter (you used this logic in notebook)
def bandpass_filter(signal, lowcut=20, highcut=300, fs=4096, order=4):
    nyquist = 0.5 * fs
    low = lowcut / nyquist
    high = highcut / nyquist
    b, a = butter(order, [low, high], btype='band')
    return filtfilt(b, a, signal)


# Whitening (your normalization approach)
def whiten_signal(signal):
    return (signal - np.mean(signal)) / np.std(signal)


# Full preprocessing pipeline (based on your sequence)
def preprocess_signal(file_path, fs=4096):
    strain, time = load_strain_data(file_path)
    filtered = bandpass_filter(strain, 20, 300, fs)
    whitened = whiten_signal(filtered)
    return whitened, time