# -*- coding: utf-8 -*-
"""visualisation/plots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QFHFETOCqwYzHZDA6KSYZbsNZIXlG0q8
"""

import matplotlib.pyplot as plt

# Plot single signal
def plot_signal(time, signal, title="Signal"):
    plt.figure(figsize=(10, 4))
    plt.plot(time, signal)
    plt.title(title)
    plt.xlabel("Time")
    plt.ylabel("Strain")
    plt.grid()
    plt.show()


# Compare raw vs processed (you had this idea in notebook plots)
def compare_signals(time, raw, processed):
    plt.figure(figsize=(10, 4))
    plt.plot(time, raw, label="Raw")
    plt.plot(time, processed, label="Processed")
    plt.legend()
    plt.title("Raw vs Processed Signal")
    plt.grid()
    plt.show()